Vagrant.configure("2") do |config|
   config.vm.box = "dvgamerr/win-xp-sp3"
   config.vm.hostname = "WindowsXP"
   config.vm.network "private_network", ip: "172.16.0.100"
   config.vm.synced_folder ".\\", "C:\\vagrant", create: true
   config.vm.provider :virtualbox do |vb|
	vb.name = "Tsunami"
	vb.memory = "1024"
   end
end 
